name: avionics
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cython=0.29.13
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libcxxabi=9.0.0
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - llvm-openmp=9.0.0
  - ncurses=6.1
  - numpy=1.17.2
  - openssl=1.1.1c
  - pip=19.2.3
  - python=3.7.3
  - readline=8.0
  - setuptools=41.2.0
  - sqlite=3.29.0
  - tk=8.6.9
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
